# Generated by Django 4.2 on 2023-04-09 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_room_hots_message_room_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='hots',
            new_name='host',
        ),
    ]
